### ISSUE TITLE
`yae init` creates a null `yae.json` which cannot be added to

### ISSUE THREAD

**Issue by ProspectPyxis** [Fuwn/yae#1]
When `yae init` is run, it creates a `yae.json` whose contents are simply `null`. This breaks `yae add`, which panics:

```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/Fuwn/yae/internal/yae.(*Environment).Add(0xc0001a6078, {0x7ffef8a3a5b5, 0x6}, {{0xc000180120, 0x57}, {0xc00012c000, 0x34}, 0x0, {0x7ffef8a3a58b, 0x3}, ...})
        github.com/Fuwn/yae/internal/yae/environment.go:19 +0xc5
main.main.Add.func7(0xc0001ae640)
        github.com/Fuwn/yae/internal/commands/add.go:106 +0x3c7
github.com/urfave/cli/v2.(*Command).Run(0xc000238160, 0xc0001ae640, {0xc0001aca00, 0xa, 0xa})
        github.com/urfave/cli/v2@v2.27.4/command.go:276 +0x97d
github.com/urfave/cli/v2.(*Command).Run(0xc0002386e0, 0xc0001ae440, {0xc00019e000, 0xb, 0xb})
        github.com/urfave/cli/v2@v2.27.4/command.go:269 +0xbb7
github.com/urfave/cli/v2.(*App).RunContext(0xc000236000, {0x401bc0, 0x6e7e60}, {0xc00019e000, 0xb, 0xb})
        github.com/urfave/cli/v2@v2.27.4/app.go:333 +0x5a5
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.27.4/app.go:307
main.main()
        github.com/Fuwn/yae/yae.go:110 +0xc65
```

Manually changing the contents of `yae.json` to `{}` fixed this issue for me.

Also, thank you for the project - this is perfect for my needs!

**Comment by Fuwn** [comment]
Thanks for reporting this, and I'm glad you're finding Yae useful! The latest commit, https://github.com/Fuwn/yae/commit/6fd049f7a0636a406d9a7405825046c1928fa8ab, should fix this.

I'm *guessing* Go or the JSON adapter hasn't been able to properly initialise the environment with safe defaults ever since schema support was added. Manually initialising the environment with a functionally empty base fixes the issue.

**Comment by ProspectPyxis** [comment]
Can confirm that the issue is now fixed, thank you!
